### ISSUE TITLE
Free accounts

### ISSUE THREAD

**Issue by 89z** [pisto/oggify#8]
Free accounts can be enabled, by vendoring librespot and changing PRODUCT_PARTNER to PRODUCT_CLIENT

**Comment by 89z** [comment]
I posted an issue to librespot  which was deleted - here is the repost in case its deleted again:


Currently this package only supports Spotify Premium accounts. This can be fixed by switching `PRODUCT_PARTNER` to `PRODUCT_CLIENT`:

https://github.com/librespot-org/librespot/blob/650d41b020691fec6c7d2c90c0f6de91ac8635cf/core/src/connection/handshake.rs#L48

https://github.com/librespot-org/librespot/blob/650d41b020691fec6c7d2c90c0f6de91ac8635cf/protocol/proto/keyexchange.proto#L22-L28

and selecting normal or low audio qualities.

**Comment by 89z** [comment]
Currently this package only supports Spotify Premium accounts. This can be fixed by switching `PRODUCT_PARTNER` to `PRODUCT_CLIENT`:

https://github.com/librespot-org/librespot/blob/650d41b020691fec6c7d2c90c0f6de91ac8635cf/core/src/connection/handshake.rs#L48

https://github.com/librespot-org/librespot/blob/650d41b020691fec6c7d2c90c0f6de91ac8635cf/protocol/proto/keyexchange.proto#L22-L28

and selecting normal or low audio qualities.

**Comment by thebiblelover7** [comment]
@89z The purpose of librespot is to enable Spotify ***Premium*** accounts to access spotify. **Not** free accounts. That is why your issue was deleted.

**Comment by 89z** [comment]
@thebiblelover7 I don't care what the purpose is. I care what is possible. If the maintainers don't want to make Free the default, that's their choice. However lying about the capabilities of the library, even if by omission, is not OK.

**Comment by thebiblelover7** [comment]
@89z I don't think they are lying about the capabilities. They do not want to get in trouble with Spotify, and so they only have Premium accounts enabled even though you can modify the source code to allow free accounts.

**Comment by 89z** [comment]
If you're selling a hammer, you can say "this hammer only works with tungsten nails". You know full well that's not true, but you have an agreement with the tungsten nail people. If anyone trys to call you out on it, you silence them. 

That's what's happening here. This is people bowing to an invisible hand, and I don't accept that. **It's lying**.
